/*
 * Copyright (C) 2017 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
*/

//                ****** Do not modify this file. ******
// This file is automatically generated by CMake. Changes should instead be
// made to cmake/gz_auto_headers.hh.in in gz-cmake

#include <gz/math/config.hh>
#include <gz/math/graph/Edge.hh>
#include <gz/math/graph/Graph.hh>
#include <gz/math/graph/GraphAlgorithms.hh>
#include <gz/math/graph/Vertex.hh>
#include <gz/math/AdditivelySeparableScalarField3.hh>
#include <gz/math/Angle.hh>
#include <gz/math/AxisAlignedBox.hh>
#include <gz/math/Box.hh>
#include <gz/math/Capsule.hh>
#include <gz/math/Color.hh>
#include <gz/math/Cone.hh>
#include <gz/math/Cylinder.hh>
#include <gz/math/DiffDriveOdometry.hh>
#include <gz/math/Ellipsoid.hh>
#include <gz/math/Filter.hh>
#include <gz/math/Frustum.hh>
#include <gz/math/GaussMarkovProcess.hh>
#include <gz/math/Helpers.hh>
#include <gz/math/Inertial.hh>
#include <gz/math/Interval.hh>
#include <gz/math/Kmeans.hh>
#include <gz/math/Line2.hh>
#include <gz/math/Line3.hh>
#include <gz/math/MassMatrix3.hh>
#include <gz/math/Material.hh>
#include <gz/math/MaterialType.hh>
#include <gz/math/Matrix3.hh>
#include <gz/math/Matrix4.hh>
#include <gz/math/Matrix6.hh>
#include <gz/math/MecanumDriveOdometry.hh>
#include <gz/math/MovingWindowFilter.hh>
#include <gz/math/OrientedBox.hh>
#include <gz/math/PID.hh>
#include <gz/math/PiecewiseScalarField3.hh>
#include <gz/math/Plane.hh>
#include <gz/math/Polynomial3.hh>
#include <gz/math/Pose3.hh>
#include <gz/math/Quaternion.hh>
#include <gz/math/Rand.hh>
#include <gz/math/Region3.hh>
#include <gz/math/RollingMean.hh>
#include <gz/math/RotationSpline.hh>
#include <gz/math/SemanticVersion.hh>
#include <gz/math/SignalStats.hh>
#include <gz/math/SpeedLimiter.hh>
#include <gz/math/Sphere.hh>
#include <gz/math/SphericalCoordinates.hh>
#include <gz/math/Spline.hh>
#include <gz/math/Stopwatch.hh>
#include <gz/math/Temperature.hh>
#include <gz/math/TimeVaryingVolumetricGrid.hh>
#include <gz/math/TimeVaryingVolumetricGridLookupField.hh>
#include <gz/math/Triangle.hh>
#include <gz/math/Triangle3.hh>
#include <gz/math/Vector2.hh>
#include <gz/math/Vector3.hh>
#include <gz/math/Vector3Stats.hh>
#include <gz/math/Vector4.hh>
#include <gz/math/VolumetricGridLookupField.hh>

