version: '3'
services:
  robo_base:
    build:
      context: ./
      dockerfile: docker/robo_base.dockerfile
    image: 192.168.5.239:5000/robo_base:latest
  robot_state_publisher:
    build:
      context: ./
      dockerfile: docker/robot_state_publisher.dockerfile
    image: robot_state_publisher:latest
    container_name: robot_state_publisher
    depends_on:
      - robo_base
    deploy:
      placement:
        constraints:
          - node.hostname == lwf-vm
#    volumes:
#      - ./your_robot.urdf:/root/your_robot.urdf
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
#    command: >
#      bash -c "source /opt/ros/humble/setup.bash &&
#               ros2 run robot_state_publisher robot_state_publisher /root/your_robot.urdf"
    command: /bin/bash -c "source /root/ros2_ws/install/setup.bash && ros2 launch lwf_robot lwf_robot.launch.py"
    network_mode: host
  realsense2_camera:
    build:
      context: ./
      dockerfile: docker/realsense.dockerfile
    image: 192.168.5.239:5000/realsense2_camera:latest
    container_name: realsense2_camera
    depends_on:
      - robo_base
    deploy:
      placement:
        constraints:
          - node.hostname == lwf-node4
    network_mode: host
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/video0:/dev/video0
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               ros2 launch realsense2_camera rs_launch.py"
  rtabmap_ros:
    build:
      context: ./
      dockerfile: docker/rtab_map.dockerfile
    image: 192.168.5.239:5000/rtabmap:latest
    container_name: rtabmap
    depends_on:
      - realsense2_camera
    deploy:
      placement:
        constraints:
          - node.hostname == lwf-node4
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               ros2 launch rtabmap_ros rtabmap.launch.py \
               depth_topic:=/camera/aligned_depth_to_color/image_raw \
               rgb_topic:=/camera/color/image_raw \
               camera_info_topic:=/camera/color/camera_info \
               frame_id:=rgbd_camera"
