version: '3'
services:
#  robo_base:
#    build:
#      context: ./
#      dockerfile: docker/robo_base.dockerfile
#    image: 192.168.5.239:5000/robo_base:latest
  robot_state_publisher:
    build:
      context: ./
      dockerfile: docker/robot_state_publisher.dockerfile
    image: robot_state_publisher:latest
    deploy:
      placement:
        constraints:
          - node.hostname == lwf-vm
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               ros2 run robot_state_publisher robot_state_publisher /root/ros2_ws/src/lwf_robot/urdf/lwf_robot.urdf"
    network_mode: host
  realsense2_camera:
    build:
      context: ./
      dockerfile: docker/realsense.dockerfile
    image: 192.168.5.239:5000/realsense2_camera:latest
    deploy:
      placement:
        constraints:
          - node.hostname == lwf-node4
    network_mode: host
    privileged: true
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
    command: >
      bash -c "source /opt/ros/humble/setup.bash && \
               ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true \
               enable_gyro:=true enable_accel:=true unite_imu_method:=2"
  rtabmap_ros:
    build:
      context: ./
      dockerfile: docker/rtab_map.dockerfile
    image: 192.168.5.239:5000/rtab_map:latest
    depends_on:
      - realsense2_camera
    deploy:
      placement:
        constraints:
          - node.hostname == lwf-vm
    network_mode: host
    ipc: "shareable"
#    volumes:
#      - /tmp/.ros:/tmp/.ros
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
      - ROS_HOME=/tmp/.ros
      - OMP_WAIT_POLICY=passive
    user: $UID
    command: >
      bash -c 'source /opt/ros/humble/setup.bash &&
               ros2 launch rtabmap_launch rtabmap.launch.py \
               rtabmap_viz:=false database_path:=/tmp/.ros/rtabmap.db \
               rtabmap_args:="--delete_db_on_start" \
               depth_topic:=/camera/aligned_depth_to_color/image_raw \
               rgb_topic:=/camera/color/image_raw \
               camera_info_topic:=/camera/color/camera_info \
               frame_id:=rgbd_camera'
