services:
  robot_state_publisher:
    build:
      context: ./
      dockerfile: docker/robot_state_publisher.dockerfile
    image: 192.168.5.239:5000/robot_state_publisher:latest
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               ros2 run robot_state_publisher robot_state_publisher /root/ros2_ws/src/lwf_robot/urdf/lwf_robot.urdf"
    network_mode: host
  slam:
    build:
      context: ./
      dockerfile: docker/lwf.dockerfile
    image: 192.168.5.239:5000/lwf:latest
#    profiles: [node4]
    network_mode: host
    ipc: "shareable"
    volumes:
      - /tmp/.ros:/tmp/.ros
      - /dev:/dev
    restart: always
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
      - ROS_HOME=/tmp/.ros
      - OMP_WAIT_POLICY=passive
    command: >
      bash -c 'source /opt/ros/humble/setup.bash && ros2 launch rtabmap_examples realsense_d435i_color.launch.py'
    lidar:
      build:
        context: ./
        dockerfile: docker/lwf.dockerfile
      image: 192.168.5.239:5000/lwf:latest
      #    profiles: [node1]
      network_mode: host
      volumes:
        - /dev/ttyUSB0:/dev/ttyUSB0
      restart: always
      privileged: true
      environment:
        - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
        - ROS_DOMAIN_ID=0
      command: >
        bash -c 'source /opt/ros/humble/setup.bash &&  ros2 launch sllidar_ros2 view_sllidar_c1_launch.py'
