---
- name: Mount /dev/nvme0n1p2 and expose it via NFS on lwf-node1, mount NFS on lwf-node2, lwf-node3, and mount NFS on lwf-vm
  hosts: all  # This assumes lwf-node1, lwf-node2, lwf-node3, and lwf-vm are defined in your inventory
  become: yes
  tasks:

  # Tasks for lwf-node1
  - name: Ensure the /home/orangepi/lwf directory exists on lwf-node1
    file:
      path: /home/orangepi/lwf
      state: directory
      owner: orangepi
      group: orangepi
      mode: '0755'
    when: inventory_hostname == 'lwf-node1'

  - name: Mount /dev/nvme0n1p2 to /home/orangepi/lwf on lwf-node1
    mount:
      src: /dev/nvme0n1p2
      path: /home/orangepi/lwf
      fstype: ext4
      state: mounted
    when: inventory_hostname == 'lwf-node1'

  - name: Ensure the mount is persistent across reboots on lwf-node1
    mount:
      src: /dev/nvme0n1p2
      path: /home/orangepi/lwf
      fstype: ext4
      opts: defaults
      state: present
    when: inventory_hostname == 'lwf-node1'

  - name: Install NFS server packages on lwf-node1
    apt:
      name: nfs-kernel-server
      state: present
      update_cache: yes
    when: inventory_hostname == 'lwf-node1'

  - name: Configure NFS export on lwf-node1
    lineinfile:
      path: /etc/exports
      line: "/home/orangepi/lwf *(rw,sync,no_root_squash)"
      create: yes
    when: inventory_hostname == 'lwf-node1'

  - name: Restart NFS service on lwf-node1 to apply changes
    service:
      name: nfs-kernel-server
      state: restarted
      enabled: yes
    when: inventory_hostname == 'lwf-node1'

  - name: Export the NFS shares on lwf-node1
    command: exportfs -arv
    when: inventory_hostname == 'lwf-node1'

  # Tasks for lwf-node2 and lwf-node3
  - name: Ensure the /home/orangepi/lwf directory exists on lwf-node2 and lwf-node3
    file:
      path: /home/orangepi/lwf
      state: directory
      owner: orangepi
      group: orangepi
      mode: '0755'
    when: inventory_hostname in ['lwf-node2', 'lwf-node3']

  - name: Install NFS client packages on lwf-node2 and lwf-node3
    apt:
      name: nfs-common
      state: present
      update_cache: yes
    when: inventory_hostname in ['lwf-node2', 'lwf-node3']

  - name: Create systemd mount unit for NFS share on lwf-node2 and lwf-node3
    copy:
      dest: /etc/systemd/system/home-orangepi-lwf.mount
      content: |
        [Unit]
        Description=NFS Mount for /home/orangepi/lwf
        Wants=network-online.target
        After=network-online.target

        [Mount]
        What=lwf-node1:/home/orangepi/lwf
        Where=/home/orangepi/lwf
        Type=nfs
        Options=defaults,_netdev,retry=5

        [Install]
        WantedBy=multi-user.target
    when: inventory_hostname in ['lwf-node2', 'lwf-node3']

  - name: Reload systemd daemon on lwf-node2 and lwf-node3
    command: systemctl daemon-reload
    when: inventory_hostname in ['lwf-node2', 'lwf-node3']

  - name: Enable and start systemd mount on lwf-node2 and lwf-node3
    systemd:
      name: home-orangepi-lwf.mount
      enabled: yes
      state: started
    when: inventory_hostname in ['lwf-node2', 'lwf-node3']

  # Tasks for lwf-vm
  - name: Ensure the /home/ros2/node_share directory exists on lwf-vm
    file:
      path: /home/ros2/node_share
      state: directory
      owner: ros2
      group: ros2
      mode: '0755'
    when: inventory_hostname == 'lwf-vm'

  - name: Install NFS client packages on lwf-vm
    apt:
      name: nfs-common
      state: present
      update_cache: yes
    when: inventory_hostname == 'lwf-vm'

  - name: Reload systemd daemon on lwf-vm
    command: systemctl daemon-reload
    when: inventory_hostname == 'lwf-vm'
