---
- hosts: all
  vars_files:
    - vault.yaml
    - ros_vars.yaml
  become: true
  become_method: sudo  # Use sudo for all nodes
  tasks:

    - name: Generate en_US.UTF-8 locale
      command: sudo locale-gen en_US en_US.UTF-8

    - name: Update locale settings
      lineinfile:
        path: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=en_US.UTF-8'
      notify: Reboot VM

    - name: Export LANG environment variable for vm
      lineinfile:
        path: /home/ros2/.bashrc
        line: 'export LANG=en_US.UTF-8'
        state: present
      when: inventory_hostname == 'lwf-vm'

    - name: Export LANG environment variable for nodes
      lineinfile:
        path: /home/orangepi/.bashrc
        line: 'export LANG=en_US.UTF-8'
        state: present
      when: inventory_hostname != 'lwf-vm'

    - name: Verify locale
      command: locale

    - name: Use a fix for map messages not working with nav2 OrangePi
      lineinfile:
        path: /home/orangepi/.bashrc
        line: 'export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp'
        state: present
      when: inventory_hostname != 'lwf-vm'

    - name: Use a fix for map messages not working with nav2 Rpi
      lineinfile:
        path: /home/rpi/.bashrc
        line: 'export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp'
        state: present
      when: inventory_hostname == 'lwf-vm'

