ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # Frequency of the filter update (in Hz)
    publish_acceleration: true
    sensor_timeout: 0.5
    two_d_mode: true  # Set to true if you want to ignore the Z axis
    publish_tf: true

    # Topic to publish the state estimation (output)
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: enu

    # IMU data topic and data to fuse
    imu0: /imu/clean_data  # Replace with the topic from your IMU publisher
    imu0_config: [ false, false, true,
                   false,  false,  true,
                   false,  false,  true,
                   true, true, true,
                   true, false, false ]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
    # Configure noise values for IMU, adjust as necessary
    imu0_linear_acceleration_z: 0.5  # Higher value dampens Z-axis variations more
    imu0_nodelay: true
    imu0_relative: true
    imu0_pose_rejection_threshold: 0.8  # Rejects values beyond this threshold
    imu0_twist_rejection_threshold: 0.8

    # RTAB-Map odometry input
    odom0: /rtabmap/odom  # Topic where RTAB-Map publishes odometry data
    odom0_config: [ true, true, true,   # [x, y, z]
                    false, false, true, # [roll, pitch, yaw]
                    true, true, true,   # [vx, vy, vz]
                    false, false, true, # [vroll, vpitch, vyaw]
                    false, false, false] # [ ax, ay, az ]
    odom0_differential: false  # Set to true if the input is in a differential form
    odom0_relative: false      # Set to true if the input is in a relative form
    odom0_queue_size: 10       # Queue size for the subscriber
#
#    # Process noise covariance matrix
#    process_noise_covariance: [ 0.05, 0,    0,    0,    0,    0,
#                                0,    0.05, 0,    0,    0,    0,
#                                0,    0,    0.05, 0,    0,    0,
#                                0,    0,    0,    0.01, 0,    0,
#                                0,    0,    0,    0,    0.01, 0,
#                                0,    0,    0,    0,    0,    0.01 ]
#
#    # Initial estimate covariance matrix
#    initial_estimate_covariance: [ 1e-9, 0,    0,    0,    0,    0,
#                                   0,    1e-9, 0,    0,    0,    0,
#                                   0,    0,    1e-9, 0,    0,    0,
#                                   0,    0,    0,    1e-9, 0,    0,
#                                   0,    0,    0,    0,    1e-9, 0,
#                                   0,    0,    0,    0,    0,    1e-9 ]
