---
- name: Sync /home/ros2/lwf from lwf-vm to all nodes
  hosts: [lwf-node1, lwf-node2, lwf-node3]
  become: yes
  tasks:
    - name: Sync /home/ros2/lwf from lwf-vm to the nodes
      synchronize:
        src: /home/ros2/lwf/   # Source directory on lwf-vm
        dest: /home/orangepi/lwf/  # Destination directory on the target nodes
        archive: yes           # Preserves permissions, symbolic links, etc.
        delete: yes            # Deletes files on the destination if not present in the source
        recursive: yes         # Recursively sync directories
        rsync_opts: "--exclude='.git' --exclude='*.log'"  # Optionally exclude some files
      delegate_to: lwf-vm       # Execute the sync from lwf-vm to the other nodes
