---
- hosts:
    - lwf_node1
    - lwf_vm
  become: true
  become_method: sudo  # Use sudo for all nodes
  tasks:
    - name: Install RpLidar Packages
      apt:
        name:
          -  ros-humble-slam-toolbox
          -  ros-humble-laser-filters
          -  ros-humble-rplidar-ros
        state: present
    - name: Launch RpLidar
      shell: |
        source /home/orangepi/lwf/ros2_ws/install/setup.bash  # Adjust the path if needed
        ros2 launch rplidar_ros launch/lwf_rplidar_launch.py
      args:
        chdir: /home/orangepi/lwf/ros2_ws  # Run the command from the workspace directory
      environment:
        RMW_IMPLEMENTATION: rmw_fastrtps_cpp  # Set environment variables if needed
      when: inventory_hostname == 'lwf_node1'
