---
- name: Build ROS 2 Workspace on lwf-vm
  hosts: lwf-vm
  become: yes
  tasks:

    - name: Change to the project directory
      command: cd /home/ros2/lwf
      args:
        chdir: /home/ros2/lwf

    - name: Stash any uncommitted changes
      command: git stash
      args:
        chdir: /home/ros2/lwf

    - name: Checkout the main branch
      command: git checkout main
      args:
        chdir: /home/ros2/lwf

    - name: Pull the latest changes from main
      command: git pull
      args:
        chdir: /home/ros2/lwf

    - name: Change to the ros2_ws directory
      command: cd ros2_ws
      args:
        chdir: /home/ros2/lwf

    - name: Install ROS dependencies using rosdep
      command: rosdep install --from-paths src --ignore-src -r -y
      args:
        chdir: /home/ros2/lwf/ros2_ws

    - name: Build the workspace using colcon
      command: colcon build
      args:
        chdir: /home/ros2/lwf/ros2_ws
      register: build_output
      ignore_errors: yes

    - name: Check if the build was successful
      fail:
        msg: "Build failed."
      when: build_output.rc != 0

    - name: Commit changes if build is successful
      command: git commit -am "Build successful"
      args:
        chdir: /home/ros2/lwf
      when: build_output.rc == 0

    - name: Push the branch back to origin
      command: git push origin main
      args:
        chdir: /home/ros2/lwf
      when: build_output.rc == 0

    - name: Apply stashed changes after the build
      command: git stash pop
      args:
        chdir: /home/ros2/lwf
